---
- hosts: all
  tasks:
    - name: Add EPEL repository
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
        gpgkey: https://getfedora.org/static/352C64E5.txt
    - name: Add Docker repository
      yum_repository:
        name: docker
        description: Docker YUM repo
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
        gpgkey: https://download.docker.com/linux/centos/gpg
    - name: Install Docker
      yum:
        name: docker-ce
        state: latest
    - name: Docker service
      service:
        name: docker
        enabled: true
        state: started
    - name: Insert Docker registry unitfile
      copy:
        src: files/docker-registry.service
        dest: /etc/systemd/system/docker-registry.service
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"
    - name: Reload systemd unit configuration
      command: systemctl daemon-reload
    - name: Start Docker registry
      service:
        name: docker-registry
        enabled: true
        state: started
